---
- name: Creates directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ adm_user }}"
    group: "{{ adm_group }}"
    mode: '0755'
    force: false
  with_items:
    - "{{ npm_home }}"
    - "{{ npm_data }}"
    - "{{ npm_data }}/cert"
    - "{{ npm_logs }}"

- name: Copy file
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ adm_user }}"
    group: "{{ adm_group }}"
    mode: '0644'
    backup: true
  with_items:
    - { src: '.env.j2', dest: '{{ npm_home }}/.env' }
    - { src: 'docker-compose.yml.j2', dest: '{{ npm_home }}/docker-compose.yml' }

- name: Restart npm
  ansible.builtin.shell: echo success
  notify:
    Restart npm
