- name: Start npm
  ansible.builtin.command: "{{ docker_compose_bin }} up --detach"
  args:
    chdir: "{{ npm_home }}"
  register: result
  changed_when: result.changed

- name: Restart npm
  ansible.builtin.shell:
    "{{ docker_compose_bin }} down; {{ docker_compose_bin }} up --detach"
  args:
    chdir: "{{ npm_home }}"
  register: result
  changed_when: result.changed
  ignore_errors: true
